#!/bin/sh

# X11 Window Manager
# ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬

# ........................................................................ bspwm

# Current multi-head monitor desktops (see .conkyrc)
if [[ $(bspc query --monitors --monitor focused) = DVI-0 ]]; then
  bspc query --desktops --desktop focused > /tmp/DVI-0
  bspc query --tree --monitor last | grep $'^\t*[0-9].*\*' | sed 's/\t\([0-9]\) .*/\1/' > /tmp/DVI-1
else
  bspc query --desktops --desktop focused > /tmp/DVI-1
  bspc query --tree --monitor last | grep $'^\t*[0-9].*\*' | sed 's/\t\([0-9]\) .*/\1/' > /tmp/DVI-0
fi
