MOUSEKEY_ENABLE = no
EXTRAKEY_ENABLE = no
CONSOLE_ENABLE = no
# COMMAND_ENABLE = no
NKRO_ENABLE = yes
# STENO_LAYERS = no
STENO_ENABLE = yes
# VIRTSER_ENABLE = yes
AUDIO_ENABLE = no
MIDI_ENABLE = no

TMPVAR := $(SRC)
SRC = $(filter-out sten.c, $(TMPVAR))
