#!/usr/bin/env python

"""
filter incoming lines based on date threshold

Threshold markers are of the form "t:YYYY-MM-DD".

This is intended to be used as TODOTXT_FINAL_FILTER.
"""

import sys
import re

from datetime import datetime, timedelta


pattern = re.compile(r"t:(\d{4})-(\d{2})-(\d{2})")

lookahead = timedelta(days=1)
def main(args=None):
	now = datetime.now() + lookahead
	for line in sys.stdin:
		match = pattern.search(line)
		if match:
			threshold = [int(i) for i in match.groups()]
			if datetime(*threshold) < now:
				print( line.strip() )
		else:
			print( line.strip() )
	return True


if __name__ == "__main__":
	status = not main(sys.argv)
	sys.exit(status)
