#!/bin/bash
# scratchpad- (see sxhkdrc)
# temporarily turn off scratchpad and return (echo) monitor it resides on

if bspc query --tree | grep -q scratchpad; then
  for i in $(bspc query --monitors); do
    if [ -n "$(bspc query --tree --monitor $i | grep scratchpad)" ]; then
      xdotool search --onlyvisible --classname scratchpad windowunmap
      echo $i
      break
    fi
  done
fi
