#!/bin/sh

# bspwm
# ▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂

# ............................................................ Status line panel

# Set panel monitor and width (don't span monitors)
. profile
[[ $(hostname) = luna ]] && M='-m DVI-0'
WIDTH=$(xrandr | grep '*' | cut -dx -f1 | sort | head -1)

# Make fifo
if [ $(pgrep -cx panel) -gt 1 ] ; then
	printf "%s\n" "The panel is already running." >&2
	exit 1
fi
trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

# Configure screen and fifo
bspc config $M bottom_padding $PANEL_HEIGHT
bspc control --subscribe > "$PANEL_FIFO" &
xtitle -sf 'T%s' > "$PANEL_FIFO" &
clock -sf 'S%A, %-d %b %-I:%M %p' > "$PANEL_FIFO" &

# Refresh!
. panel_colors
cat "$PANEL_FIFO" | panel_bar | bar -b -g ${WIDTH}x$PANEL_HEIGHT -f "$PANEL_FONT_FAMILY" -F "$COLOR_FOREGROUND" -B "$COLOR_BACKGROUND" &
wait
