#!/usr/bin/dash
# sdothum - 2016 (c) wtfpl

# nnn Plugin
# ══════════════════════════════════════════════════════════════════════════════

# ....................................................... mount removable device

ls $HOME/mtp/* 2>/dev/null && exit
mtp mount

# vim: set ft=sh: #
