#!/usr/bin/dash
# sdothum - 2016 (c) wtfpl

# nnn Plugin
# ══════════════════════════════════════════════════════════════════════════════

# ................................................................. Jump refresh

# fcache PWD
env SUBTREE=pwd $(dirname $0)/jump $@  # see .jump:caches

# vim: set ft=sh: #
