#!/bin/sh

# bspwm
# ▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂

# ................................................................ Presel window

# wait for application then presel window for next application
# usage: presel application up|down|left|right [seconds]
if waitfor $1 $3; then
  bspc window $(bspc query -T | grep $1 | awk '{ print $4; }') --focus
  bspc window --presel $2
fi



