#!/bin/bash

# herbstluftwm
# ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬

# Note: the common Qwerty "IJKL" key mappings are remapped to a WASD layout
#       for the Colemak Mod-DH keyboard layout to "MNLE"
#       see https://colemakmods.github.io/mod-dh/
#           http://thedarnedestthing.com/colemak%20shift-dh#ergo-layout

# ................................................................... Initialize

# chain herbstclient commands
hc() {
  cmds="$cmds , $@"
}

dohc() {
  # foreground process by default
  herbstclient chain $cmds
  unset cmds
}

# if you have a super key you will be much happier with Mod set to Mod4
Mod=Mod1    # Use alt as the main modifier
# Mod=Mod4   # Use the super key as the main modifier

hc emit_hook reload
# hsetroot -solid '#464F52'

herbstclient set tree_style '╾│ ├└╼─┐'

# remove all existing keybindings and rules
hc keyunbind --all
hc unrule -F

# unlock, just to be sure
hc unlock

# split/remove frame created by herbstluftwm on startup to apply custom default_frame_layout
# see http://herbstluftwm.org/faq.html#_q_i_set_default_frame_layout_to_my_favorite_layout_but_it_doesn_8217_t_work_with_the_root_frame_existing_frames
hc split vertical 0.5 && hc remove

# ......................................................................... Tags

tag_names=( {0..9} )
tag_keys=( {0..9} )

# custom default_frame_layout must be set before tags are added
[[ $(hostname) = monad ]] && hc set default_frame_layout 2 || hc set default_frame_layout 1
hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]}
do
  hc add "${tag_names[$i]}"
  key="${tag_keys[$i]}"
  if ! [ -z "$key" ] ; then
    hc keybind "$Mod-$key"       use_index "$i"
    hc keybind "$Mod-Shift-$key" move_index "$i"
  fi
done

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
hc detect_monitors
# hc set auto_detect_monitors 1

# tags must complete initialization before hc loads
dohc

# the load command cannot be chained and only be invoked explicitly 
# because the quoted layout parameter cannot be expanded as a single parameter by shell
if [[ $(hostname) = luna ]]; then
  # herbstclient load "1" '(split horizontal:0.570000:0 (clients vertical:0) (clients vertical:0))' &
  herbstclient load "1" '(split horizontal:0.500000:0 (clients vertical:0) (clients vertical:0))' &
  # herbstclient load "2" '(split horizontal:0.500000:0 (clients vertical:0) (clients vertical:0))' &
  herbstclient load "2" '(clients max:0)' &
  herbstclient load "3" '(split horizontal:0.500000:0 (clients vertical:0) (clients vertical:0))' &
  herbstclient load "4" '(split horizontal:0.500000:0 (clients vertical:0) (clients vertical:0))' &
  herbstclient load "5" '(split horizontal:0.500000:0 (clients vertical:0) (clients vertical:0))' &
  herbstclient load "6" '(clients horizontal:0)' &
  herbstclient load "8" '(split horizontal:0.500000:0 (clients vertical:0) (clients vertical:0))' &
fi

# ........................................................................ Rules

hc rule focus=on    # normally focus new clients
# hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
# hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)'                    focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)'     pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG'                      focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

# hc set swap_monitors_to_get_tag    0
hc rule class=blackscreen            focus=on monitor=1 fullscreen=on
hc rule class=tabbed                 tag=1 index=0 focus=on
hc rule class=dwb                    tag=1
hc rule class=luakit                 tag=1
hc rule class=qutebrowser            tag=1
hc rule title=RSS                    tag=1 index=1 focus=off
hc rule class=Minitube               tag=1
hc rule title=IRC                    tag=2 index=1 focus=on
hc rule title=Messenger              tag=2 index=0 focus=off
hc rule class=Pidgin                 tag=2
hc rule title=Twitter                tag=2
hc rule class=Geary                  tag=3
hc rule title=IMAP                   tag=3
hc rule title=Mail                   tag=3 index=0 focus=on
hc rule title=TODO                   tag=3 index=1 focus=off
hc rule title=Usenet                 tag=3
# hc rule class=Surf                 tag=4
hc rule class=Vimb                   tag=4 index=1 focus=off once
hc rule windowrole=thedarnedestthing tag=4 index=0 focus=on
hc rule class=mplayer2               tag=5
hc rule class=Pavucontrol            tag=5 index=1 focus=off
hc rule class=Xfce4-mixer            tag=5
hc rule class=Mixer                  tag=5
hc rule title=Music                  tag=5 index=0 focus=on
hc rule title=Radio                  tag=5 index=1 focus=off
hc rule class=Rrip_gui               tag=5 focus=on switchtag=on
hc rule class=Smplayer               tag=6 monitor=0 focus=on switchtag=on fullscreen=on
hc rule class=Umplayer               tag=6 monitor=0 focus=on switchtag=on fullscreen=on
hc rule class=Kodi                   tag=6 monitor=0 focus=on switchtag=on fullscreen=on
hc rule class=Gimp                   tag=7 monitor=0 focus=on switchtag=on
hc rule class=Darktable              tag=7 monitor=0 focus=on switchtag=on fullscreen=on
hc rule class=Digikam                tag=7 monitor=0 focus=on switchtag=on
hc rule class=VirtualBox             tag=7 monitor=0 focus=on switchtag=on
# hc rule class=Thunar               tag=8 focus=on switchtag=on
hc rule class=Tixati                 tag=8 index=0 focus=on
hc rule class=Transmission-gtk       tag=8 index=0
hc rule title=NZB                    tag=8 index=0 focus=off

# special apps and dialogues
hc rule class=Amphetype              pseudotile=on
hc rule title=blackscreen            monitor=1 fullscreen=on
hc rule class=File-roller            pseudotile=off
hc rule class=float                  focus=on pseudotile=on
hc rule class=Gvim                   focus=on switchtag=on hook=max
hc rule class=Klavaro                pseudotile=on
# trap urxvt -name=max
hc rule instance=max                 focus=on switchtag=on hook=max
hc rule class=mpv                    focus=on switchtag=on fullscreen=on
hc rule class=ROX-Filer              pseudotile=off
hc rule class=Savebox                pseudotile=off
# hc rule title=scratchpad           pseudotile=on
hc rule class=Vlc                    focus=on switchtag=on fullscreen=on
# hc rule class=Zathura              pseudotile=off

dohc &

# ........................................................ Applications keybinds

hc keybind $Mod-Return               chain . emit_hook open_window . spawn scratchpad
hc keybind $Mod-Shift-Return         chain . emit_hook open_window . spawn urxvt -title 'terminal' -name 'terminal'
hc keybind Super-Return              chain . emit_hook open_window . spawn dman
hc keybind Super-Shift-Return        chain . emit_hook open_window . spawn dzshelp
hc keybind Super-space               chain . emit_hook open_window . spawn dmenu_run
hc keybind Super-Shift-space         chain . emit_hook open_window . spawn dsystemd
hc keybind Super-Tab                 chain . emit_hook open_window . spawn dhlwm
hc keybind Super-Control-Tab         chain . emit_hook open_window . spawn dhlwm bring
hc keybind $Mod-grave                chain . emit_hook open_window . spawn rox
# hc keybind Super-minus             spawn pactl set-sink-volume 0 -5%
# hc keybind Super-Shift-minus       spawn pactl set-sink-volume 0 +5%
hc keybind Super-bracketleft         spawn pactl set-sink-volume 0 -5%
hc keybind Super-bracketright        spawn pactl set-sink-volume 0 +5%
hc keybind Super-0                   spawn pactl set-sink-mute 0 toggle
hc keybind Super-Shift-0             spawn pactl set-sink-volume 0 100%
hc keybind Super-1                   spawn dalarm
hc keybind Super-equal               spawn dcalc
hc keybind Super-slash               chain . emit_hook open_window . spawn dfiles
hc keybind Super-Shift-slash         chain . emit_hook open_window . spawn dfolders
hc keybind $Mod-backslash            spawn toggle_conky
hc keybind $Mod-Control-backslash    spawn toggle_compton
hc keybind $Mod-Shift-backslash      spawn toggle_unclutter
hc keybind Super-F1                  spawn dtest
hc keybind Super-a                   spawn dabook
hc keybind Super-b                   spawn dbookmarks
hc keybind Super-c                   chain . emit_hook open_window . spawn dconfigs
hc keybind Super-d                   chain . emit_hook open_window . spawn ddict
hc keybind Super-e                   chain . emit_hook open_window . spawn dedit
hc keybind Super-f                   chain . emit_hook open_window . spawn dzsh
hc keybind Super-h                   spawn dhistory
hc keybind Super-j                   chain . emit_hook open_window . spawn djournals
hc keybind Super-Shift-j             chain . emit_hook open_window . spawn djournals follow
hc keybind Super-l                   chain . emit_hook open_window . spawn dlogs
hc keybind Super-Shift-l             chain . emit_hook open_window . spawn dlogs follow
hc keybind Super-m                   spawn dmusic
hc keybind Super-p                   chain . emit_hook open_window . spawn notepad
hc keybind Super-Shift-p             spawn dpass
hc keybind Super-q                   spawn clack
hc keybind Super-Shift-q             spawn clack swap
hc keybind Super-s                   chain . emit_hook open_window . spawn dscripts
hc keybind Super-t                   chain . emit_hook open_window . spawn typingtutor amphetype
hc keybind Super-Shift-t             chain . emit_hook open_window . spawn typingtutor klavaro
hc keybind Super-v                   spawn toggle_cinema
hc keybind Super-Control-v           spawn dscreensaver
hc keybind Super-w                   chain . emit_hook open_window . spawn vimb
hc keybind Super-x                   spawn dhalt
hc keybind Super-z                   spawn dzshist
hc keybind Control-Shift-F1          spawn keymap_toggle

# .................................................................. Keybindings

# window manager
hc keybind $Mod-Shift-q              quit
hc keybind $Mod-Shift-r              reload
hc keybind $Mod-d                    spawn redraw
hc keybind $Mod-w                    chain . close_or_remove . emit_hook close_window

# focusing clients
hc keybind $Mod-Left                 focus -e left
hc keybind $Mod-Down                 focus -e down
hc keybind $Mod-Up                   focus -e up
hc keybind $Mod-Right                focus -e right
# hc keybind $Mod-h                  focus left
# hc keybind $Mod-j                  focus down
# hc keybind $Mod-k                  focus up
# hc keybind $Mod-l                  focus right
hc keybind $Mod-m                    focus left
hc keybind $Mod-n                    focus down
hc keybind $Mod-l                    focus up
hc keybind $Mod-e                    focus right
hc keybind $Mod-bracketleft          focus_monitor 1
hc keybind $Mod-bracketright         focus_monitor 0

# moving clients
hc keybind $Mod-Shift-Left           shift -e left
hc keybind $Mod-Shift-Down           shift -e down
hc keybind $Mod-Shift-Up             shift -e up
hc keybind $Mod-Shift-Right          shift -e right
# hc keybind $Mod-Shift-h            shift left
# hc keybind $Mod-Shift-j            shift down
# hc keybind $Mod-Shift-k            shift up
# hc keybind $Mod-Shift-l            shift right
hc keybind $Mod-Shift-m              shift left
hc keybind $Mod-Shift-n              shift down
hc keybind $Mod-Shift-l              shift up
hc keybind $Mod-Shift-e              shift right
hc keybind $Mod-Shift-bracketleft    spawn swap_window 1
hc keybind $Mod-Shift-bracketright   spawn swap_window 0
hc keybind $Mod-Control-bracketleft  spawn swap_monitors 1
hc keybind $Mod-Control-bracketright spawn swap_monitors 0

# splitting frames
# create an empty frame at the specified direction
hc keybind $Mod-u                    split bottom 0.5
hc keybind $Mod-o                    split right  0.5
hc keybind $Mod-Shift-u              chain . split bottom 0.5 . cycle_frame 1
hc keybind $Mod-Shift-o              chain . split right  0.5 . cycle_frame 1
# let the current frame explode into subframes
hc keybind $Mod-Control-space        split explode
hc keybind $Mod-Shift-comma          rotate
hc keybind $Mod-Shift-period         chain . lock . rotate . rotate . rotate . unlock
hc keybind $Mod-Shift-slash          chain . lock . rotate . rotate  . unlock

# resizing frames
resizestep=0.025
# hc keybind $Mod-Control-h          resize left  +$resizestep
# hc keybind $Mod-Control-j          resize down  +$resizestep
# hc keybind $Mod-Control-k          resize up    +$resizestep
# hc keybind $Mod-Control-l          resize right +$resizestep
hc keybind $Mod-Control-m            resize left  +$resizestep
hc keybind $Mod-Control-n            resize down  +$resizestep
hc keybind $Mod-Control-l            resize up    +$resizestep
hc keybind $Mod-Control-e            resize right +$resizestep
hc keybind $Mod-Control-Left         resize left  +$resizestep
hc keybind $Mod-Control-Down         resize down  +$resizestep
hc keybind $Mod-Control-Up           resize up    +$resizestep
hc keybind $Mod-Control-Right        resize right +$resizestep

# cycle through tags
hc keybind $Mod-Control-period       use_index +1 --skip-visible
hc keybind $Mod-Control-comma        use_index -1 --skip-visible
hc keybind $Mod-BackSpace            use_previous

# layouting
hc keybind $Mod-r                    remove
hc keybind $Mod-space                chain . spawn toggle_max        . emit_hook focus_changed
hc keybind $Mod-Shift-space          chain . spawn cycle_layout      . emit_hook focus_changed
hc keybind $Mod-s                    chain . floating toggle         . emit_hook focus_changed
hc keybind $Mod-f                    chain . spawn toggle_fullscreen . emit_hook focus_changed
hc keybind $Mod-p                    chain . pseudotile toggle       . emit_hook focus_changed
# hc keybind $Mod-m                  spawn hide_window +1
# hc keybind $Mod-Control-m          spawn hide_window -1
# hc keybind $Mod-Shift-m            spawn hide_window 0
hc keybind $Mod-h                    spawn hide_window +1
hc keybind $Mod-Control-h            spawn hide_window -1
hc keybind $Mod-Control-Shift-h      spawn hide_window 0
hc keybind $Mod-Shift-h              spawn hide_window

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1            move
hc mousebind $Mod-Button2            zoom
hc mousebind $Mod-Button3            resize
hc set focus_follows_mouse           1

# focus
hc keybind $Mod-apostrophe           cycle_monitor
hc keybind $Mod-Tab                  cycle_all +1
hc keybind $Mod-Shift-Tab            cycle_all -1
hc keybind $Mod-c                    cycle +1
hc keybind $Mod-Shift-c              cycle -1
hc keybind $Mod-period               cycle_frame +1
hc keybind $Mod-comma                cycle_frame -1
hc keybind $Mod-i                    jumpto urgent

dohc &

# ........................................................................ Theme

# set for compton transparency rules, see .compton.conf
hc attr theme.tiling.reset           1
hc attr theme.floating.reset         1
hc set frame_border_active_color     '#222222'
hc set frame_border_normal_color     '#101010'
hc set frame_bg_normal_color         '#565656'
hc set frame_bg_active_color         '#345F0C'
hc set frame_border_width            0
hc set always_show_frame             0
hc set frame_bg_transparent          1
hc set frame_transparent_width       0
hc set frame_gap                     18

# hc attr theme.active.color         '#BAC2C4'
# hc attr theme.normal.color         '#5E6B6E'
hc attr theme.active.color           '#93E0F7'
hc attr theme.normal.color           '#BAC2C4'
hc attr theme.urgent.color           orange
hc attr theme.inner_width            0
hc attr theme.inner_color            black
# hc attr theme.border_width         3
hc attr theme.border_width           11
hc attr theme.outer_width            1
hc attr theme.outer_color            '#141414'
hc attr theme.floating.border_width  11
# hc attr theme.floating.outer_width 1
hc attr theme.floating.outer_width   1
hc attr theme.floating.outer_color   '#141414'
# hc attr theme.active.inner_color   '#3E4A00'
# hc attr theme.active.outer_color   '#3E4A00'
# hc attr theme.background_color     '#141414'

hc set window_gap                    17
hc set frame_padding                 0
hc set gapless_grid                  0
hc set smart_frame_surroundings      0
hc set smart_window_surroundings     0
hc set mouse_recenter_gap            0

# if [[ $(hostname) == monad ]]; then
#   hc attr theme.active.color         '#ef255b'
#   hc attr theme.normal.color         '#4d6600'
#   hc attr theme.border_width         3
#   hc set frame_gap                   0
#   hc set window_gap                  0
# fi

dohc &

# ........................................................................ Panel

# find the panel
# panel=~/.config/herbstluftwm/panel.sh
# [ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
# for monitor in $(herbstclient list_monitors | cut -d: -f1)
# do
#   # start it on each monitor
#   "$panel" $monitor &
# done

# ................................................................ Startup suite

# session startup stuff, see .xinitrc
[[ -e /tmp/herbstluftwm.lock ]] || ~/bin/autostart
touch /tmp/herbstluftwm.lock
xdotool search --sync --onlyvisible --classname $BROWSER
if [[ $(hostname) = luna ]]; then
  herbstclient chain . focus_monitor 1 . use 2
  herbstclient chain . focus_monitor 0 . use 1
else
  herbstclient use 1
fi

# ........................................................................ Hooks

# herbstclient --idle '(hook 1|hook 2|..)' | while read; do something; done
herbstclient --idle '(close_window|focus_changed|max|open_window)' | while read hook name winid
do
  echo "hc --idle => $hook $name $winid"
  [[ $hook = open_window ]] && open_window
  [[ $hook = close_window ]] && close_window
  [[ $name = max ]] && herbstclient set_layout max
  # pulsing borders is a background process loop
  [[ $hook = focus_changed ]] && set_border &
done

