#!/bin/sh

# herbstluftwm
# ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬

# ................................................................. Focus window

# focus active or hidden window
# Usage: dhlwm focus (switch to window)
#        dhlwm bring (bring window to current tag)

[[ $* ]] && mode='Raise' || mode='Focus'
visible='□'
hidden='–'

attr() {
  herbstclient attr clients.$2.$1
}

instance() {
  attr "instance" "$@"
}

tag() {
  # tags represented as box tag, empty box as hidden tick'tag
  tag=$(attr "tag" "$@")
  echo $tag | grep -q "'" && echo " $hidden ${tag#\'}" || echo " $visible $tag"
}

for i in $(herbstclient attr clients | grep '0x')
do
  window="$(tag $i):$(instance $i)$(tag $i):$i"
  echo window="$(tag $i):$(instance $i)$(tag $i):$i"
  [[ $windows ]] && windows="$windows\n$window" || windows="$window"
done

if window=$(echo -e $windows | sort | cut -d: -f2 | $(dwrapper) -p "$mode Window"); then
  window=$(echo -e $windows | grep "$window")
  tag=$(echo $window | sed "s/.* [$visible$hidden] \([0-9]\):0x.*/\1/")
  # bring window
  if [[ $* ]]; then
    herbstclient bring "$(echo $window | sed 's/.*:\(.*\)/\1/')"
  elif echo $window | grep " $visible [0-9]:0x"; then
    # focus normal tag
    herbstclient chain . use "$tag" . jumpto "$(echo $window | sed 's/.*:\(.*\)/\1/')"
  else
    # focus (restore) tick'tag
    herbstclient chain . use "$tag" . bring "$(echo $window | sed 's/.*:\(.*\)/\1/')"
  fi
  echo $window | grep " $hidden [0-9]:0x" && merge_tag $tag
fi
