#!/bin/sh

# herbstluftwm
# ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬

# .................................................................... Emit hook

[[ $(pgrep -cx emit_hook) -gt 2 ]] && exit
touch ~/.dynamic

# herbstclient --idle ['(hook|..)']| while read hook name winid
herbstclient --idle '(focus_window|focus_changed|rule|focus_frame)' | while read hook name winid
do
  echo "hc --idle => $hook $name $winid"
  case $name in
    # max)  herbstclient chain . jumpto $winid .set_layout max & ;;
    max)  herbstclient set_layout max & ;;
    *)    case $hook in
            focus_window)   [[ -e ~/.dynamic ]] && focus_window & ;;
            focus_changed)  set_border & ;;
            focus_frame)    [[ -e ~/.dynamic ]] && focus_frame & ;;
          esac
          ;;
  esac
done
