#!/bin/sh

# herbstluftwm
# ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬

# ................................ Find empty subframe to open (spawn) window in

focus_frame() {
  herbstclient cycle_frame -1

  for i in $(seq 1 $(herbstclient attr tags.by-name.$tag.frame_count))
  do
    herbstclient cycle_frame 1
    (( $(herbstclient attr tags.by-name.$tag.curframe_wcount) )) || break
  done
}

# .............................................. Focus non-empty subframe window

focus_window() {
  frames=$(herbstclient attr tags.by-name.$tag.frame_count)
  herbstclient cycle_frame -1

  for i in $(seq 1 $frames)
  do
    herbstclient cycle_frame 1
    (( $(herbstclient attr tags.by-name.$tag.curframe_wcount) )) && break
    # empty desktop, return to original frame
    [[ $i -eq $frames ]] && herbstclient cycle_frame 1
  done
}

# focus
# ▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔

tag=$(herbstclient attr monitors.focus.tag)

case $@ in
  frame)    focus_frame ;;
  window)   focus_window ;;
  *)        echo ".. focus  frame | window" ;;
esac
