#!/bin/sh

# herbstluftwm
# ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬

# .............................................................. On close window

# focus non-empty subframe
tag=$(herbstclient attr monitors.focus.tag)
frames=$(herbstclient attr tags.by-name.$tag.frame_count)
# action now triggered by emit_hook (script)
# herbstclient close_or_remove

herbstclient cycle_frame -1
for i in $(seq 1 $frames)
do
  herbstclient cycle_frame 1
  (( $(herbstclient attr tags.by-name.$tag.curframe_wcount) )) && break
  # empty desktop, return to original frame
  [[ $i -eq $frames ]] && herbstclient cycle_frame 1
done
