#!/usr/bin/dash
# [ $TRACE ] && CHILD="hide $@" . $PARENT

# herbstluftwm
# ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬

# .............................................................. Hide operations

# Usage: hide [msg], see functions/hide

TAG=$(herbstclient attr monitors.focus.tag)

msg=$1
shift
if [ -e ${0%/hide}/functions/hide/$msg ] ;then
  . ${0%/hide}/functions/hide/$msg $@
else
  usage $0
fi

# vim: set ft=sh: #
