#!/bin/sh

# herbstluftwm
# ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬

# ............................................................. Smart move_index

# move window to non-empty tag subframe and focus next window
winid=$(herbstclient attr clients.focus.winid)
herbstclient chain . lock . use $@
focus frame
herbstclient chain . bring $winid . use_previous . unlock
focus window
