#!/usr/bin/dash
[ $TRACE ] && CHILD="on $@" . $PARENT

# herbstluftwm
# ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬

# ....................................................... Conditional operations

msg=$1
shift
if [ -e ${0%/on}/functions/on/$msg ] ;then
  . ${0%/on}/functions/on/$msg $@
else
  usage $0
fi

# vim: set ft=sh: #
