#!/bin/sh

# herbstluftwm
# ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬

# .................................................................. Desktop tag

# see .conkyrc
name=$(herbstclient attr clients.focus.instance)
[[ $(echo $name | wc -w) -eq 1 ]] && echo $name || herbstclient attr clients.focus.class
