#!/bin/sh

# herbstluftwm
# ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬

# .................................................................. Desktop tag

query_desktop() {
  [[ $@ = focus ]] || focus=-v
  herbstclient list_monitors | grep $focus '\[FOCUS\]' | cut -d'"' -f2
}

# ................................................................ Hidden window

query_hidden() {
  herbstclient dump "'$(query desktop $@)" >/dev/null 2>&1 && echo 'hidden'
}

# ................................................................. Release 'tag

# for conky hidden desktop windows highlighting
query_tag() {
  [[ $(herbstclient dump "'$@" | wc -w) -le 2 ]] && herbstclient merge_tag "'$@"
}

# .................................................................. Desktop tag

query_window() {
  name=$(herbstclient attr clients.focus.instance)
  [[ $(echo $name | wc -w) -eq 1 ]] && echo $name || herbstclient attr clients.focus.class
}

# conky query, see .conkyrc
# ▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔

case $1 in
  desktop)  query_desktop $2 ;;
  hidden)   query_hidden $2 ;;
  "'tag")   query_tag  $2 ;;
  window)   query_window ;;
  *)        echo ".. query  desktop [focus] | hidden [focus] | 'tag | window" ;;
esac
