#!/bin/sh

# herbstluftwm
# ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬

# ....................................................... Redraw desktop padding

# dynamic desktop width with conky panel
conky_monitor() {
  if [[ $(herbstclient attr clients.focus.fullscreen) = true ]]; then
    draw monitor conky fullscreen
  else
    draw monitor conky
  fi
}

if [[ $(xrandr | grep '*' | cut -dx -f1 | sort | tail -1) -gt 1024 ]]; then
  if xdotool search --onlyvisible --classname 'Conky'; then
    if herbstclient list_monitors | grep '^0:.*\[FOCUS\]'; then
      conky_monitor
    else
      herbstclient chain lock . focus_monitor 0
      conky_monitor
      herbstclient chain . focus_monitor 1 . unlock
    fi
  else
    [[ $(herbstclient attr clients.focus.fullscreen) = true ]] \
      && draw monitor fullscreen \
    || draw monitor fullframe
  fi
fi
