#!/bin/sh

# herbstluftwm
# ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬

# ................................................................ Swap monitors

# swap tag and focus to monitor
swap_to() {
  # view tag on selected monitor
  swap_monitors=$(herbstclient get swap_monitors_to_get_tag)
  herbstclient set swap_monitors_to_get_tag 1
  (( $@ )) && swap="focus_monitor 0 . use $tag1 . focus_monitor 1 . use $tag0" \
           || swap="focus_monitor 1 . use $tag0 . focus_monitor 0 . use $tag1"
  herbstclient chain . lock . $swap . unlock
  herbstclient set swap_monitors_to_get_tag $swap_monitors
}

direction=$@
focus=$(herbstclient list_monitors | grep '\[FOCUS\]' | cut -d: -f1)
tag0=$(herbstclient list_monitors | grep '^0:' | cut -d'"' -f2)
tag1=$(herbstclient list_monitors | grep '^1:' | cut -d'"' -f2)

if [[ $focus = $direction ]]; then
  [[ $focus = 0 ]] && swap_to 0 || swap_to 1
else
  [[ $focus = 0 ]] && swap_to 1 || swap_to 0
fi
