#!/bin/sh

# herbstluftwm
# ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬

# ............................................................. Smart move_index

# move window to non-empty tag subframe and focus next window
switch_index() {
  winid=$(herbstclient attr clients.focus.winid)
  herbstclient chain . lock . use $@
  focus frame
  herbstclient chain . bring $winid . use_previous . unlock
  focus window
}

# ........................................................... Smart cycle layout

switch_layout() {
  # skip grid if only 2 windows in subframe (layout is effectively same as horizontal)
  if [[ $(herbstclient layout | grep '\[FOCUS\]' | cut -d: -f2 | cut -d'[' -f1 | wc -w) -eq 2 ]]; then
    herbstclient cycle_layout 1 vertical horizontal
  else
    herbstclient cycle_layout 1 vertical grid horizontal
  fi
}

# .............................................................. Switch monitors

# switch tag and focus to monitor
switch_to() {
  # view tag on selected monitor
  swap_monitors=$(herbstclient get swap_monitors_to_get_tag)
  herbstclient set swap_monitors_to_get_tag 1
  (( $@ )) && switch="focus_monitor 0 . use $tag1 . focus_monitor 1 . use $tag0" \
           || switch="focus_monitor 1 . use $tag0 . focus_monitor 0 . use $tag1"
  herbstclient chain . lock . $switch . unlock
  herbstclient set swap_monitors_to_get_tag $swap_monitors
}

switch_monitor() {
  direction=$@
  focus=$(herbstclient list_monitors | grep '\[FOCUS\]' | cut -d: -f1)
  tag0=$(herbstclient list_monitors | grep '^0:' | cut -d'"' -f2)
  tag1=$(herbstclient list_monitors | grep '^1:' | cut -d'"' -f2)

  if [[ $focus = $direction ]]; then
    [[ $focus = 0 ]] && switch_to 0 || switch_to 1
  else
    [[ $focus = 0 ]] && switch_to 1 || switch_to 0
  fi
}

# .......................................................... Smart switch window

# move window to non-empty tag subframe (and focus next window)
switch_frame() {
  herbstclient chain . lock . focus_monitor $1
  focus frame
  herbstclient chain . bring $winid . focus_monitor $2 . unlock
  focus window
}

switch_window() {
  # switch window and focus to monitor (0,1)
  direction=$@
  focus=$(herbstclient attr monitors.focus.index)
  winid=$(herbstclient attr clients.focus.winid)

  if [[ $focus -eq $direction ]]; then
    [[ $focus -eq 0 ]] && switch_frame 1 0 || switch_frame 0 1
  else
    [[ $focus -eq 0 ]] && switch_frame 1 1 || switch_frame 0 0
  fi
}

# switch
# ▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔

case $1 in
  index)    switch_index $2 ;;
  layout)   switch_layout ;;
  monitor)  switch_monitor $2 ;;
  window)   switch_window $2 ;;
  *)        echo ".. switch  index (0-9) | layout | monitor (0|1) | window (0|1)" ;;
esac
