#!/bin/sh

# herbstluftwm
# ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬

# ...................................................... Toggle conky fullscreen

# fullscreen with conky panel
herbstclient lock
if [[ $(xrandr | grep '*' | cut -dx -f1 | sort | tail -1) -gt 1024 ]]; then
  if herbstclient list_monitors | grep '^0:.*\[FOCUS\]'; then
    if xdotool search --onlyvisible --classname 'Conky'; then
      [[ $(herbstclient attr clients.focus.fullscreen) = true ]] \
        && set_monitors conky \
      || set_monitors conky fullscreen
    else
      # handle frame no conky
      [[ $(herbstclient attr clients.focus.fullscreen) = true ]] \
        && set_monitors fullframe \
      || set_monitors fullscreen
    fi
  else
    [[ $(herbstclient attr clients.focus.fullscreen) = true ]] \
      && set_monitors secondary \
    || set_monitors secondary fullscreen
  fi
fi
herbstclient chain . fullscreen toggle . unlock
