#!/bin/sh

# X11 System
# ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬

# .................................................................. Cinema mode

# toggle / black out (secondary) screen
if [[ $(herbstclient list_monitors | wc -l) -gt 1 ]]; then
  if xdotool search --onlyvisible --classname 'blackscreen'; then
    kill -9 $(pgrep -f blackscreen)
    dscreensaver on
  else
    # cleanup any black screens on other desktops
    pgrep -f blackscreen && kill -9 $(pgrep -f blackscreen)
    # for toggling, spawn own urxvt instance (not client)
    SHELL=/bin/sh /usr/bin/urxvt -sh 10 -fg black -bg black -cr black -title 'blackscreen' -name 'blackscreen' &
    set_monitors secondary fullscreen
    dscreensaver off
  fi
else
  dscreensaver
fi
