#!/bin/sh

# herbstluftwm
# ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬

# ............................................................ Toggle max layout

if [[ $(herbstclient attr clients.focus.fullscreen) = true ]]; then
  toggle_fullscreen
else
  layout=$(herbstclient dump '' '@' | sed 's/[^ ]* \([^:]*\).*/\1/')
  tag=/tmp/herbstluftwm:tag:$(herbstclient attr monitors.focus.tag)
  if [[ $layout != max ]]; then
    echo $layout > $tag
    herbstclient set_layout max
  elif [[ -e $tag ]]; then
    herbstclient set_layout $(< $tag)
    rm -f $tag
  else
    herbstclient cycle_layout 1
  fi
fi
