#!/bin/sh

# herbstluftwm
# ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬

# ............................................................. Toggle unclutter

if pidof unclutter; then
  killall unclutter
  herbstclient set focus_follows_mouse 1
else
  # add delay for tabbed vim
  [[ -e ~/.unclutter ]] && sleep $(< ~/.unclutter)
  unclutter -idle 1 -jitter 2 -root &
  herbstclient set focus_follows_mouse 0
fi
