#!/bin/sh

# herbstluftwm
# ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬

# ............................................................... Emit hook trap

# wait for hook completion (necessary for non-interactive window manipulations)
process=$(echo $@ | tr '_' ' ')
herbstclient emit_hook $@

# trap hook..
if [[ -e ~/.dynamic ]] ;then
  while ! pgrep -f "$process"
  do
    sleep 0.001s
  done

  # ..then wait for completion
  while pgrep -f "$process"
  do
    sleep 0.001s
  done
fi
