#!/bin/sh

# herbstluftwm
# ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬

# ............................................................ Status line panel

# set panel monitor and width (don't span monitors)
source ${0%panel}/panel_colors
WIDTH=$(xrandr | grep '*' | cut -dx -f1 | sort | head -1)

# make fifo
(( $(pgrep -cx panelbar) )) && exit
trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

# configure screen and fifo
herbstclient --idle '.*_changed' > "$PANEL_FIFO" &
xtitle -sf 'T%s' > "$PANEL_FIFO" &
clock -sf "S%A  %-d %b '%y    %-I:%M %p" > "$PANEL_FIFO" &

# refresh!
cat "$PANEL_FIFO" | panel_bar | lemonbar -b -g ${WIDTH}x$PANEL_HEIGHT -f "$PANEL_FONT_FAMILY" -F "$COLOR_FOREGROUND" -B "$COLOR_BACKGROUND" &
wait
