#!/bin/sh

# herbstluftwm
# ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬

# ................................................................. LemonBoy bar

# desktop tag id padding
pad="  "

# fifo read loop
while read -r line
do
	case $line in
    *_changed*) active=$(query_desktop focus)
                inactive=$(query_desktop)
                unset tags
		            for i in $(herbstclient attr clients | grep '0x')
                do
                  tags="$tags $(herbstclient attr clients.$i.tag)"
                done
                unset desktops
                for i in $(seq 1 9) 0
                do
                  if echo "$tags" | grep -q "$i"; then
                    echo "$tags" | grep -q " $i" && visible=true || unset visible
                    echo "$tags" | grep -q "'$i" && hidden=true || unset hidden
                    if [[ $i -eq $active ]]; then
                      format="%{B$COLOR_ACTIVE_BG}"
                      [[ $visible ]] && format="${format}%{F$COLOR_OCCUPIED_FG}" || format="${format}%{F$COLOR_FREE_FG}"
                      [[ $hidden ]] && format="${format}${pad}%{U$COLOR_HIDDEN_FG}%{+u}"
                    elif [[ $i -eq $inactive ]]; then
                      format="%{B$COLOR_INACTIVE_BG}"
                      [[ $visible ]] && format="${format}%{F$COLOR_OCCUPIED_FG}" || format="${format}%{F$COLOR_FREE_FG}"
                      [[ $hidden ]] && format="${format}${pad}%{U$COLOR_HIDDEN_FG}%{+u}"
                    else
                      format="%{B$COLOR_BACKGROUND}"
                      [[ $visible ]] && format="${format}%{F$COLOR_OCCUPIED_FG}" || format="${format}%{F$COLOR_FREE_FG}"
                      [[ $hidden ]] && format="${format}${pad}%{U$COLOR_HIDDEN_FG}%{+u}"
                    fi
                  else
                    unset visible
                    unset hidden
                    if [[ $i -eq $active ]]; then
                      format="%{F$COLOR_FREE_FG}%{B$COLOR_ACTIVE_BG}"
                    elif [[ $i -eq $inactive ]]; then
                      format="%{F$COLOR_FREE_FG}%{B$COLOR_INACTIVE_BG}"
                    else
                      format="%{F$COLOR_FREE_FG}%{B$COLOR_BACKGROUND}"
                    fi
                  fi
                  [[ $hidden ]] && unset leader || leader="${pad}"
                  desktops="${desktops}${format}${leader}${i}%{-u}  %{U-}%{B-}%{F-}"
                done
                ;;
		S*)         system="%{F$COLOR_FREE_FG}%{B$COLOR_STATUS_BG} ${line#?} %{B-}%{F-}" ;;
    T*)         title="%{F$COLOR_FREE_FG}%{B$COLOR_TITLE_BG} $(query_window) %{B-}%{F-}" ;;
	esac
	# printf "%s\n" "%{l}${desktops}%{c}${title}%{r}${system}"
	printf "%s\n" "%{l}${title}%{c}${desktops}%{r}${system}"
done
