#!/usr/bin/dash
# sdothum - 2016 (c) wtfpl
# [ $TRACE ] && CHILD="focus $@" . $PARENT

# herbstluftwm
# ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬

# ............................................................. Focus operations

# Usage: focus <msg>, see functions/focus

# dmenu functions
. $HOME/bin/dmenu

TAG=$(herbstclient attr monitors.focus.tag)

msg=$1
shift
if [ -e ${0%/focus}/functions/focus/$msg ] ;then
  . ${0%/focus}/functions/focus/$msg $@
else
  usage $0
fi

# vim: set ft=sh: #
