#!/usr/bin/dash
# sdothum - 2016 (c) wtfpl
# [ $TRACE ] && CHILD="focus $@" . $PARENT

# herbstluftwm
# ▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂

# ............................................................. Focus operations

# Usage: focus <msg> [<options>*], see functions/focus

# dmenu functions
. $HOME/bin/dmenu

TAG=$(herbstclient attr monitors.focus.tag)

msg=$1
[ $msg ] && shift || usage $0
if [ -e ${0%/focus}/functions/focus/$msg ] ;then
  . ${0%/focus}/functions/focus/$msg $@
  # force panel refresh
  xtitle -f 'T%s
' >$(cat $PANEL_FIFO)
elif which $msg >/dev/null 2>&1 ;then
  # dynamic app window creation
  [ -e $DYNAMIC ] && focus frame
  $msg $@ &
else
  usage $0
fi

# vim: set ft=sh: #
