#!/usr/bin/dash
# [ $TRACE ] && CHILD="is $@" . $PARENT

# herbstluftwm
# ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬

# ........................................................ Is (state) operations

# Usage: is <msg>, see functions/is

msg=$1
shift
if [ -e ${0%/is}/functions/is/$msg ] ;then
  . ${0%/is}/functions/is/$msg $@
else
  usage $0
fi

# vim: set ft=sh: #
