#!/usr/bin/dash
# sdothum - 2016 (c) wtfpl
# [ $TRACE ] && CHILD="is $@" . $PARENT

# herbstluftwm
# ══════════════════════════════════════════════════════════════════════════════

# ........................................................ Is (state) operations

# Usage: is <msg>, see functions/is

msg=$1
[ $msg ] && shift || usage $0
if [ -e $(dirname $0)/functions/is/$msg ] ;then
  . $(dirname $0)/functions/is/$msg $@
else
  usage $0
fi

# vim: set ft=sh: #
