#!/usr/bin/dash
# [ $TRACE ] && CHILD="pin $@" . $PARENT

# herbstluftwm
# ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬

# ............................................................ pin operations

# Usage: pin [msg], see functions/pin

msg=$1
shift
if [ -e ${0%/pin}/functions/pin/$msg ] ;then
  . ${0%/pin}/functions/pin/$msg $@
else
  usage $0
fi
herbstclient emit_hook focus_changed

# vim: set ft=sh: #
