#!/usr/bin/dash
# sdothum - 2016 (c) wtfpl
# [ $TRACE ] && CHILD="query $@" . $PARENT

# herbstluftwm
# ══════════════════════════════════════════════════════════════════════════════

# ............................................................. Query operations

# Usage: query <msg>, see functions/query

msg=$1
[ $msg ] && shift || usage $0
if [ -e ${0%/query}/functions/query/$msg ] ;then
  . ${0%/query}/functions/query/$msg $@
else
  usage $0
fi

# vim: set ft=sh: #
