#!/usr/bin/dash
# [ $TRACE ] && CHILD="query $@" . $PARENT

# herbstluftwm
# ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬

# ............................................................. Query operations

# Usage: query <msg>, see functions/query

msg=$1
shift
if [ -e ${0%/query}/functions/query/$msg ] ;then
  . ${0%/query}/functions/query/$msg $@
else
  usage $0
fi

# vim: set ft=sh: #
