#!/usr/bin/env bash
# 2009-2011 Paul Mansfield
# License: GPL, http://www.gnu.org/copyleft/gpl.html
# modified from projectview by Steven Hum to iterate over @contexts

# Stop Verbose lines, thanks to Mark Harrison
TODOTXT_VERBOSE=0

# Check how we are being run
HOWRUN=$(basename $0)

# If being run as simplepv then turn off all colours.
# Useful for display outside of terminal
if [ $HOWRUN = "simplepv" ] ; then
    TODOTXT_PLAIN=1
    PRI_X=$NONE
    PRI_A=$NONE
    PRI_B=$NONE
    PRI_C=$NONE
    DEFAULT=$NONE
    COLOR_DONE=$NONE
fi

action=$1
shift

# Stop filter now and run in a controlled manner after the _list function is run
TODOTXT_DISABLE_FILTER=1 

[ "$action" = "usage" ] && {
    echo "  Customized context view:"
    echo "    $(basename $0) [TERM...]"
    echo "      Show todo items containing TERM, grouped by context, and displayed in"
    echo "      priority order. If no TERM provided, displays entire todo.txt."
    echo ""
    exit
}

# Show contexts in alphabetical order and todo items in priority order
echo "=====  Contexts  ====="
echo ""

# Find all contexts and sort
CONTEXTS=$(grep -o '[^ ]*@[^ ]\+' "$TODO_FILE" | grep '^@' | sort -u | sed 's/^@//g' )

# For each context show header and the list of todo items
for context in $CONTEXTS ; do 
    # Use core _list function, does numbering and colouring for us
    CONTEXT_LIST=$(_list "$TODO_FILE" "@$context\b" "$@" | sed 's/\ *@[a-zA-Z0-9._\-]*\ */ /g')
    if [[ -n "${CONTEXT_LIST}" ]]; then
        echo  "---  $context  ---"
        echo  "${CONTEXT_LIST}" | eval $TODOTXT_FINAL_FILTER 
        # If run as simplepv don't add newlines
        if [ $HOWRUN != "simplepv" ] ; then
            echo  ""
        fi
    fi
done

# Show todo items not associated to a context
CONTEXT_LIST=$(_list "$TODO_FILE" "$@" | grep -v "@\w" )
if [[ -n "${CONTEXT_LIST}" ]]; then
    echo "--- No contexts for ---"
    echo "${CONTEXT_LIST}" | eval $TODOTXT_FINAL_FILTER
fi
