#!/usr/bin/env bash

action=$1
shift

function usage() {
  echo "  Customized edit item:"
	echo "    $(basename $0) [item]"
	echo "      Edit item(s) using text editor."
	echo ""
	exit
}

[ "$action" = "usage" ] && usage

cmd=${EDITOR:-vi}
if [[ "$1" =~ ^[0-9]+$ ]]; then
	cmd="$cmd +$1"
fi

$cmd "$TODO_FILE"
