#!/usr/bin/env bash
# 2009-2011 Paul Mansfield
# License: GPL, http://www.gnu.org/copyleft/gpl.html

# Stop Verbose lines, thanks to Mark Harrison
TODOTXT_VERBOSE=0
# Allow control of wrapping if using as simplepv action
NOWRAP=0

# Check how we are being run
HOWRUN=$(basename $0)

# move arguments one to left, therefore eating action name
action=$1
shift

# If being run as simplepv then turn off all colours and
# wrap at 40 characters
# Useful for display outside of terminal
if [ $HOWRUN = "simplepv" ] ; then
    TODOTXT_PLAIN=1
    PRI_X=$NONE
    PRI_A=$NONE
    PRI_B=$NONE
    PRI_C=$NONE
    DEFAULT=$NONE
    COLOR_DONE=$NONE
    # Check if we want to wrap text or not
    if [ "$1" = "--nowrap" ]; then
        NOWRAP=1
        shift
    fi
    # If we have fmt then use it to wrap long lines
    $(file /usr/bin/fmt > /dev/null 2>&1) 
    FMT=$?
    # Set final filter
    if [ "$NOWRAP" -eq 1 ] ; then
        TODOTXT_FINAL_FILTER="$TODOTXT_FINAL_FILTER "
    elif [ $FMT -eq 0 ] ; then
        TODOTXT_FINAL_FILTER="$TODOTXT_FINAL_FILTER | fmt -t -w 40"
    fi
fi

# Stop filter now and run in a controlled manner after the _list function is run
TODOTXT_DISABLE_FILTER=1 

[ "$action" = "usage" ] && {
    echo "  Customized project view:"
    echo "    $(basename $0) [TERM...]"
    echo "      Show todo items containing TERM, grouped by project, and displayed in"
    echo "      priority order. If no TERM provided, displays entire todo.txt."
    echo ""
    exit
}

# Show projects in alphabetical order and todo items in priority order
echo "=====  Projects  ====="
echo ""

# Find all projects and sort
PROJECTS=$(grep -o '[^ ]*+[^ ]\+' "$TODO_FILE" | grep '^+' | sort -u | sed 's/^+//g' )

# For each project show header and the list of todo items
for project in $PROJECTS ; do 
    # Use core _list function, does numbering and colouring for us
    PROJECT_LIST=$(_list "$TODO_FILE" "+$project\b" "$@" | sed 's/\ *+[a-zA-Z0-9._\-]*\ */ /g')
    if [[ -n "${PROJECT_LIST}" ]]; then
        echo  "---  $project  ---"
        echo  "${PROJECT_LIST}" | eval $TODOTXT_FINAL_FILTER 
        # If run as simplepv don't add newlines
        if [ $HOWRUN != "simplepv" ] ; then
            echo  ""
        fi
    fi
done

# Show todo items not associated to a project
PROJECT_LIST=$(_list "$TODO_FILE" "$@" | grep -v "+[[:alnum:]]*" )
if [[ -n "${PROJECT_LIST}" ]]; then
    echo "--- Not in projects ---"
    echo "${PROJECT_LIST}" | eval $TODOTXT_FINAL_FILTER
fi
